var host=window.location.host;var proto=window.location.protocol;var pathArray=window.location.pathname.split('/');var secondLevelLocation=pathArray[1];var ajax_url=proto+'//'+host;ajax_url=ajax_url+'/'+secondLevelLocation;$(document).ajaxStart(function(){$('#loading').show();}).ajaxStop(function(){$('#loading').hide();});$(document).ready(function(){$.validator.addMethod("letters",function(value,element){return this.optional(element)||/^[a-z]+$/i.test(value);},"Letters only please");$('#loading').hide();$("#flashmsg").fadeOut(10000);$("#mailAddress").hide();$("#paypalLink").slideDown();$("#paymentChoose").change(function(){if($(this).val()=='Mailed Check'){$("#paypalLink").hide();$("#mailAddress").slideDown();$("#mailAdd").addClass("required");}else if($(this).val()=='Paypal'){$("#mailAddress").hide();$("#paypalLink").slideDown();$("#paypalmail").addClass("required");}});$("#MemberAddeventForm").validate();var memberid=$('#Memberid').val();$("#MemberRegmemberForm").validate({rules:{"data[Member][group_id]":{required:true},"data[userMeta][fname]":{required:true,letters:true},"data[userMeta][lname]":{required:true,letters:true},"data[Member][email]":{required:true,email:true,remote:ajax_url+"/members/checkMemberExist?memberid="+memberid}},messages:{"data[Member][group_id]":{required:"Please select userType"},"data[userMeta][fname]":{required:"First Name cannot be blank "},"data[userMeta][lname]":{required:"Last Name cannot be blank"},"data[Member][email]":{required:"Please enter your email",email:"Please enter a valid email address",remote:"Email already exist"}}});$("#MemberStep1").validate({rules:{"data[Member][studentEmail]":{required:true,email:true}},messages:{"data[Member][studentEmail]":{required:"Please enter Email id",email:"Invalid Email ID"}}});$("#MemberStep2").validate();$("#MemberStep3").validate({rules:{"data[Member][amount]":{required:true,digits:true}}});$('#tutorPaypal').validate({rules:{"data[Member][payment]":{required:true},"data[Member][paymentFrequency]":{required:true}},messages:{"data[Member][payment]":{required:"Please select payment option"},"data[Member][paymentFrequency]":{required:"Please select payment frequency"}}});$("form#AdminLogin").submit(function(){if($('#AdminLogin').validate().form()){var uname=$('#adminuser').attr('value');var upass=$('#pass').attr('value');var thisHref=ajax_url+"/members/checkadminlogin/";var attributes=uname+'/'+upass;$.post(thisHref,$("form#AdminLogin").serialize(),function(data){if(jQuery.trim(data)=="authorized"){window.location.reload();}else{$('div#loginAlert').html(data);$('div#loginAlert').show(500);return false;}});}
return false;});if($("input#adminuser").length){$("input#adminuser").focus(function(){$('div#loginAlert').hide(300);});}
if($("input#pass").length){$("input#pass").focus(function(){$('div#loginAlert').hide(300);});}
if($("#MemberGroupId").length){$("#MemberGroupId").focus(function(){$('div#loginAlert').hide(300);});}
$("#menu li ul").hide();$("#menu li").hover(function(){$(this).children("ul").show();},function(){$(this).children("ul").hide();});$("#MemberEditForm").validate();$("#UserAddForm").validate({rules:{"data[Member][email]":{required:true,email:true,remote:ajax_url+"/Members/checkemail/"},"data[Member][cPassword]":{required:true,equalTo:'#MemberPwd'},"data[Member][school_id]":{required:true,remote:ajax_url+"/Members/checkeschool/"}},messages:{"data[Member][email]":{required:'This field is required',email:'Please enter valid email.',remote:'Email Already Exist'},"data[Member][cPassword]":{required:'This field is required',equalTo:'Password not Match'},"data[Member][school_id]":{required:'This field is required',remote:'School Already Exist'}}});$("#ChangePasswordForm").validate({rules:{"data[Member][cPassword]":{required:true,equalTo:'#AdminPassword1'}},messages:{"data[Member][cPassword]":{required:'This field is required',equalTo:'Password not Match'}}});$("#SchoolAddForm").validate({rules:{"data[School][slug]":{required:true,remote:ajax_url+"/Schools/checkslug/"},"data[School][school_name]":{required:true,remote:ajax_url+"/admin/Schools/checkname/"},"data[School][file]":{accept:"(jpe?g|gif|png)"},"data[School][file1]":{accept:"(jpe?g|gif|png)"}},messages:{"data[School][slug]":{required:'This field is required',remote:'slug Already Exist'},"data[School][school_name]":{required:'This Field is required',remote:'This School already exist'},"data[School][file]":{accept:'Please Upload Image File ( jpeg,gif,png )'},"data[School][file1]":{accept:'Please Upload Image File ( jpeg,gif,png )'}}});var schoolId=$('#schoolid').val();$("#SchoolEditForm").validate({rules:{"data[School][slug]":{required:true,remote:ajax_url+"/Schools/checkeditslug/?schoolId="+schoolId},"data[School][school_name]":{required:true,remote:ajax_url+"/Schools/checkeditname/?schoolId="+schoolId},"data[School][file]":{accept:"(jpe?g|gif|png)"},"data[School][file1]":{accept:"(jpe?g|gif|png)"}},messages:{"data[School][slug]":{required:'This field is required',remote:'slug Already Exist'},"data[School][school_name]":{required:'This field is required',remote:'slug Already Exist'},"data[School][file]":{accept:'Please Upload Image File ( jpeg,gif,png )'},"data[School][file1]":{accept:'Please Upload Image File ( jpeg,gif,png )'}}});$("div.paging a").live("click",function(){var formId=$(this).parents('form').attr('id');var divId=$(this).parents('div').attr('id');$("#loading").show();if($(formId).length!==0){loadPiece({href:$(this).attr("href"),divName:"#pagingDivParent",callback:function(){setCheckBoxes(formId);}});}else{loadPiece({href:$(this).attr("href"),divName:"#pagingDivParent",callback:function(){setCheckBoxes(formId);}});}
return false;});function loadPiece(obj){if($("#pagingStatus").length!=='0'){$("#pagingStatus").val(obj.href);}
$(obj.divName).load(unescape(obj.href),{},function(){$("#loading").fadeOut('slow');if(obj.callback){obj.callback();}
setUserDeleteEvent();var formId=$(this).parents('form').attr('id');var divPaginationLinks=obj.divName+" .paging a";$(divPaginationLinks).click(function(){$("#ajax-loading").show();var thisHref=$(this).attr("href");loadPiece({href:thisHref,divName:obj.divName,callback:function(){setCheckBoxes(formId);if(obj.callback){obj.callback();}else{'';}}});return false;});});}
setUserDeleteEvent();setCheckBoxes('UserViewForm');function setCheckBoxes(form){$("#"+form+" input[type='checkbox']:first").click(function(){if($(this).is(":checked")){$("#"+form+" input[type='checkbox']").each(function(){$(this).attr("checked","checked");});}else{$("#"+form+" input[type='checkbox']").each(function(){$(this).attr("checked","");});}});$("#"+form+" input[type='checkbox']").click(function(){if(!$(this).is(":checked")){$("#"+form+" input[type='checkbox']:first").attr('checked','');}});}
$(".slide_toggle").click(function(){if($(".slide_toggle").text()=='Filter data (click to show)'){$(".slide_toggle").text('Filter data (click to hide)');}else{$(".slide_toggle").text('Filter data (click to show)');}
$(".slide").slideToggle("slow");});$(".slide_toggle").mouseover(function(){$(".slide_toggle").css({"background-color":"#B3BBC2","font-color":"#000000"});});$(".slide_toggle").mouseout(function(){$(".slide_toggle").css("background-color","#e5eecc");});$(".slide").hide();$(".expandGrid").click(function(){if($('#mid-col').attr('class')=="addWidth"){$(this).text("EXPAND GRID");$('#left-col').show(0);$('#mid-col').animate({width:'737px'},0,function(){$(this).removeClass('addWidth');});}else{$(this).text("SHRINK GRID");$('#mid-col').css('width','');$('#left-col').hide();$('#mid-col').attr('class','addWidth').css('width','100%').show();}});function setUserDeleteEvent(){if($("#pagingDivParent .delete-single-user").length){$("#pagingDivParent .table-delete-link").click(function(){var id=$(this).attr('id');if(confirm('Are you sure you want to delete this user')){deleteSingleRecord(id,"/admin/members/delete/");}});}
if($("#pagingDivParent .delete-single-course").length){$("#pagingDivParent .table-delete-link").click(function(){var id=$(this).attr('id');if(confirm('Are you sure you want to delete this course')){deleteCourseRecord(id,"/admin/schools/courseDelete/");}});}
if($("#pagingDivParent .delete-single-school").length){$("#pagingDivParent .table-delete-link").click(function(){var id=$(this).attr('id');if(confirm('Are you sure you want to delete this school')){deleteSchoolRecord(id,"/admin/schools/delete/");}});}
if($("#pagingDivParent .delete-single-faq").length){$("#pagingDivParent .table-delete-link").click(function(){var id=$(this).attr('id');if(confirm('Are you sure you want to delete this school')){deleteSchoolRecord(id,"/admin/faqs/faqDelete/");}});}}
function deleteSingleRecord(id,url){if($("#pagingStatus").val()===''){$("#pagingStatus").val(ajax_url+'/admin/members/memberView');}
$("#loading").show();var delId=id.replace("del_","");$.ajax({type:"GET",url:ajax_url+url+delId,data:'',success:function(html){if(jQuery.trim(html)=="deleted"){$("#loading").fadeOut('slow');$("#del_"+delId).parents('tr').fadeOut('slow',function(){$("#del_"+id).remove();});loadPiece({href:$("#pagingStatus").val(),divName:"#pagingDivParent",callback:function(){setCheckBoxes('UserViewForm');}});}}});}
function deleteCourseRecord(id,url){if($("#pagingStatus").val()===''){$("#pagingStatus").val(ajax_url+'/admin/schools/courseView/');}
$("#loading").show();var delId=id.replace("del_","");$.ajax({type:"GET",url:ajax_url+url+delId,data:'',success:function(html){if(jQuery.trim(html)=="deleted"){$("#loading").fadeOut('slow');$("#del_"+delId).parents('tr').fadeOut('slow',function(){$("#del_"+id).remove();})
loadPiece({href:$("#pagingStatus").val(),divName:"#pagingDivParent",callback:function(){setCheckBoxes('UserViewForm');}});}}});}
function deleteSchoolRecord(id,url){if($("#pagingStatus").val()===''){$("#pagingStatus").val(ajax_url+'/admin/schools/view/');}
$("#loading").show();var delId=id.replace("del_","");$.ajax({type:"GET",url:ajax_url+url+delId,data:'',success:function(html){if(jQuery.trim(html)=="deleted"){$("#loading").fadeOut('slow');$("#del_"+delId).parents('tr').fadeOut('slow',function(){$("#del_"+id).remove();})
loadPiece({href:$("#pagingStatus").val(),divName:"#pagingDivParent",callback:function(){}});}}});}
function deleteFaqRecord(id,url){if($("#pagingStatus").val()===''){$("#pagingStatus").val(ajax_url+'/admin/faqs/faqView/');}
$("#loading").show();var delId=id.replace("del_","");$.ajax({type:"GET",url:ajax_url+url+delId,data:'',success:function(html){if(jQuery.trim(html)=="deleted"){$("#loading").fadeOut('slow');$("#del_"+delId).parents('tr').fadeOut('slow',function(){$("#del_"+id).remove();})
loadPiece({href:$("#pagingStatus").val(),divName:"#pagingDivParent",callback:function(){}});}}});}
var schoolId=$('#schoolid').val();$("#SchoolCourseEditForm").validate({rules:{"data[Course][course_id]":{required:true,remote:ajax_url+"/Schools/checkeditcourseid/?schoolId="+schoolId},"data[Course][course_title]":{required:true,remote:ajax_url+"/Schools/checkeditcoursename/?schoolId="+schoolId}},messages:{"data[Course][course_id]":{required:'This field is required',remote:'CourseId Already Exist'},"data[Course][course_title]":{required:'This field is required',remote:'Course Name Already Exist'}}});var schoolId=$('#schoolid').val();$('#formsubmitbutton').click(function(){checkCourseId(function(response){if(response){$('#SchoolCourseAddForm').submit();}});});function checkCourseId(callback){var dataurl=ajax_url+"/Schools/checkcourseid/";var schoolId=$('#courseaddschoolId').val();var courseCode=$('#courseCode').val();$('#schoolMsg').text('');$('#courseCodeMsg').text('');$('#courseTitleMsg').text('');if(schoolId===""){$('#schoolMsg').text("Please select school");}else if(courseCode===""){$('#courseCodeMsg').text("Please enter course code");}else{$.ajax({type:"POST",url:dataurl,async:true,data:"&schoolId="+schoolId+"&courseCode="+courseCode,success:function(response){if(parseInt(response,10)>0){$('#courseCodeMsg').text("Course code already exist");return false;}else{checkCourseName(function(get){callback(true);})}}});}}
function checkCourseName(callback){var dataurl=ajax_url+"/Schools/checkcoursename/";var schoolId=$('#courseaddschoolId').val();var courseName=$('#course_title').val();if(courseName===""){$('#courseTitleMsg').text("Please enter course name");}else{$.ajax({type:"POST",url:dataurl,data:"&schoolId="+schoolId+"&courseCode="+courseName,success:function(response){if(parseInt(response,10)>0){$('#courseTitleMsg').text("Course name already exist");return false;}else{callback(response)}}});}}
$("#SchoolAddAssignCourseForm").validate();$("#uploads").validate({rules:{"data[Course][school_id]":{required:true},"action_file":{accept:"(xls)"}},messages:{"data[Course][school_id]":{required:'This field is required'},"action_file":{accept:'Please Upload Excel File'}}});$("#Causeschool").validate();$("#Studentschool").validate();$("#MemberTestingForm").validate();$("#MemberBookTutorCourseForm").validate();$("#TutCourseEditschoolinfoForm").validate({rules:{"data[TutCourse][course_id]":{required:true},"data[TutCourse][rate]":{required:true}},messages:{"data[TutCourse][course_id]":{required:"Please Enter the Course"},"data[TutCourse][rate]":{required:"Please Enter the rate"}}});if($(".datepicker").length){var dates=$('#DateFrom, #DateTo').datepicker({defaultDate:"+1w",changeMonth:true,changeYear:true,dateFormat:"yy-mm-dd",numberOfMonths:1,onSelect:function(selectedDate){var option=this.id=="DateFrom"?"minDate":"maxDate";var instance=$(this).data("datepicker");var date=$.datepicker.parseDate(instance.settings.dateFormat||$.datepicker._defaults.dateFormat,selectedDate,instance.settings);dates.not(this).datepicker("option",option,date);}});}});